version: 1.0.{build}
image: Ubuntu
build_script:
  - sh: sudo apt-get update && sudo apt-get install -y sudo git gcc g++ build-essential cmake bash curl uuid-dev && sudo rm -rf /var/lib/apt/lists/*
  - sh: git submodule update --init --recursive
test_script:
  - sh: bash -eo pipefail test.sh cov
  - sh: cd build/CMakeFiles/qryptext.dir/src && bash <(curl -s https://codecov.io/bash)
